/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;

import java.text.SimpleDateFormat;  
import java.util.Date; 
import java.util.ArrayList;

import koneksi.koneksi;
/**
 *
 * @author Global Store
 */
public class menabung extends javax.swing.JFrame {

    
    public Connection conn = new koneksi().connect();
    /**
     * Creates new form menabung
     */
    ArrayList<String> data = new ArrayList<>();
    
    public void getSaldo()
    {
        String query = "SELECT (SUM(uang_masuk) - SUM(uang_keluar)) as saldo FROM tabungan where nrp="+login.txtnrp.getText()+"";
        String saldo = "";
        try {
            Statement stmt = conn.createStatement();
            ResultSet hasil = stmt.executeQuery(query);
            if(hasil.next())
            {
//                jika dia tidak pernah nabung sama sekali maka label akan ditampilkan 0 
                if (hasil.getInt("saldo") == 0) {
                    txtsaldoanda2.setText(hasil.getString("0"));
                }
                else
                {
                    txtsaldoanda2.setText(hasil.getString("saldo"));
                }
            }
        } catch (Exception e) {
        }
    }
    
    public menabung() {
        initComponents();
        getSaldo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtisi = new javax.swing.JTextField();
        btnYa = new javax.swing.JButton();
        txtkembali = new javax.swing.JButton();
        txtsaldoanda = new javax.swing.JLabel();
        txtkeluar = new javax.swing.JButton();
        txtsaldoanda2 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menabung");

        jLabel2.setText("Masukkan jumlah uang yang anda ingin masukkan");

        txtisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtisiActionPerformed(evt);
            }
        });

        btnYa.setText("YA");
        btnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYaActionPerformed(evt);
            }
        });

        txtkembali.setText("KEMBALI KEMENU SEBELIMNYA");
        txtkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembaliActionPerformed(evt);
            }
        });

        txtsaldoanda.setText("Saldo Anda ");

        txtkeluar.setText("KELUAR");
        txtkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeluarActionPerformed(evt);
            }
        });

        txtsaldoanda2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnYa)
                        .addGap(18, 18, 18)
                        .addComponent(txtkembali)
                        .addGap(18, 18, 18)
                        .addComponent(txtkeluar))
                    .addComponent(txtisi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtsaldoanda)
                        .addGap(18, 18, 18)
                        .addComponent(txtsaldoanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsaldoanda)
                    .addComponent(txtsaldoanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYa)
                    .addComponent(txtkembali)
                    .addComponent(txtkeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtisiActionPerformed

    private void txtkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembaliActionPerformed
       new form_master().setVisible(true); // memindahkan dari menabung form ke form_master
       this.setVisible(false);
    }//GEN-LAST:event_txtkembaliActionPerformed

    private void txtkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeluarActionPerformed
        new login().setVisible(true);
       this.setVisible(false); 
    }//GEN-LAST:event_txtkeluarActionPerformed

    private void btnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYaActionPerformed
        // TODO add your handling code here:
        int tabung = Integer.parseInt(txtisi.getText());
        if (tabung < 0) {
            JOptionPane.showMessageDialog(null, "MAAF SALDO YANG ANDA MASUKKAN TIDAK WAJAR");
        } else {
        
            String query = "INSERT INTO tabungan VALUES(?,?,?,?)";

            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyy HH:mm:ss");
            Date date = new Date();

            try { 
                data.clear();
                String nrp = login.txtnrp.getText();
                data.add(nrp);
                data.add(txtisi.getText());
                data.add("0");
                data.add(date.toString());

                PreparedStatement stmt = conn.prepareStatement(query);
                for (int i = 0; i < data.size(); i++) {
                    stmt.setString((i+1), data.get(i));
                }


                stmt.executeUpdate();

    //            JOptionPane.showMessageDialog(null, "Berhasil Menabung");
                getSaldo();
                txtisi.setText("");
            } catch (Exception e) {
                System.out.println("Error : " + e);
            }
        }
    }//GEN-LAST:event_btnYaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menabung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtisi;
    private javax.swing.JButton txtkeluar;
    private javax.swing.JButton txtkembali;
    private javax.swing.JLabel txtsaldoanda;
    private javax.swing.JLabel txtsaldoanda2;
    // End of variables declaration//GEN-END:variables
}
